name = "GreedyCraft"
author = "TCreopargh"
version = "1.35.2.118.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "985805ecad5783ac7d1379a6dbf7de4d3c32be2d6e081e0875fbd2f34e167479"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
